### ISSUE TITLE
Final video of project

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#104]
Urobiť video o našom projekte spolu s popisom a výzvami, ktorými sme čelili.

**Comment by N4gyR** [comment]
[LCR 4191a controller.zip](https://github.com/TIS2020-FMFI/hp/files/5972217/LCR.4191a.controller.zip)
@pavelpetrovic

**Comment by pavelpetrovic** [comment]
ďakujem, je to bezchybné! super!

**Comment by jakubzzak** [comment]
# cal
<img width="1024" alt="calibration_example" src="https://user-images.githubusercontent.com/45845462/107849561-67777400-6dfc-11eb-8c21-97c4bab8a8ef.png">

# measurement
<img width="1124" alt="measurement_example" src="https://user-images.githubusercontent.com/45845462/107849587-90980480-6dfc-11eb-8078-978c8c6409db.png">
