### ISSUE TITLE
abs in displayA handling

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#127]

**Comment by JanPastorek** [comment]
mazeme teda? tiez nevidim moznost ako to urobit, jedine ze by aplikacia urobila absolutnu hodnotu z daneho measurement

**Comment by pavelpetrovic** [comment]
čoto? čo to?

**Comment by JanPastorek** [comment]
> čoto? čo to?
@pavelpetrovic , nevieme ako to spraviť, stroj aspoň čo sme hľadali, neponúka taký command, čo by to spustil.

**Comment by pavelpetrovic** [comment]
no ale čo máte na mysli, je to niektorá požiadavka? ktoré číslo?
