### ISSUE TITLE
when pressed run button, change tab if the other tab is visible

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#152]

**Comment by JanPastorek** [comment]
je nám ten tab vlastne treba? lebo ved aj tak obidve nemozu naraz bezat cize ani tahat data z tab, neduplikujeme tak zbytocne? @jakubzzak

**Comment by jakubzzak** [comment]
@janpastorek pointa je v tom, že potrebujeme zobraziť parametre merania, či už toho čo beží alebo toho čo načítame, mohli sme to spraviť formou komentára, takto je to však prehľadnejšie, elegantnejšie a vyzerá to dobre.. prečo tak rozmýšľaš? komplikuje to niečo?

**Comment by JanPastorek** [comment]
@jakubzzak  aha chapem, cize ide o ten load, ja som myslel, ze sa to robi kvoli upperRun a lowerRun a to mi prislo ako duplikacia
