### ISSUE TITLE
null pointer when loading graph

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#196]
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/45845462/105733814-3ceb7700-5f32-11eb-8f51-ef90c2eb234b.png">

**Comment by JanPastorek** [comment]
@MariaRiya vies sa na to pozriet? do stvrtka nech to stihneme vsetko :)

**Comment by MariaRiya** [comment]
jasne) pozriem sa na to
