### ISSUE TITLE
podrobný dátový model perzistentných údajov

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#23]

**Comment by JanPastorek** [comment]
https://drive.google.com/file/d/16oGA-US4nKNJJkTNFzNLoSpzv0GpsqRT/view?usp=sharing

**Comment by JanPastorek** [comment]
https://docs.google.com/document/d/1joi-2bbQwqkxOh1a5-xu9SD5lCwfg0sUCV487t9o3Zg/edit#

**Comment by jakubzzak** [comment]
*marked with ? => not sure*
- [ ] čo sa týka config suboru, niektóre veci nebudeme potrebovať, ako napr. DsplayA/B_ref, interpolation
- [ ] config bude vlastne init parametrov, ktoré teda neviem či chceš aj ukladať po ich zmene, alebo budú vždy rovnaké, v každom prípade trigger mode = internal, manual sweep = off, auto sweep = on, high speed = off ?, zvyšok podľa obrázka 1.1.0 z dokumentácie
- [ ] resolution parametru nerozumiem :/
- [ ] namerané data budú ukladané v súbore ../year/month/day/time-type.txt, obsahovať bude 3 stĺpce s nameranými dátami, frekvencia, Display A, display B oddelené \tab no taktiež bude obsahovať komentáre na začiatku súboru, kde si autor môže zadať nejakú poznámku, no uložia sa tu aj detaily merania potrebné pre jeho identifikaciu
- [ ] aplikácia bude vedieť aj exportovať meranie, čo v konečnom dôsledku iba prekopíruje obsah z .txt do napr. .csv a odstráni všetky komentáre, ak si to bude iný program vyžadovať, budeme musieť upraviť aj formátovanie dát

**Comment by jakubzzak** [comment]
No a čo sa týka kalibrácie, v aplikácii treba prístroj pred meraním nakalibrovať, viď dokumentáciu bod 3.1.3.1, kde budeme len posielať príkazy do prístroja, teda nič ukladať nebude treba, no opäť dávam ?, pretože ešte nemáme naštudovanú komunikáciu s prístrojom

**Comment by JanPastorek** [comment]
vďaka za komenty, poupravujem.
