### ISSUE TITLE
auto save button showing the whole path doesn't fit

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#235]
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/45845462/106390862-c1cf0880-63ea-11eb-81ba-bad81232bea0.png">

**Comment by JanPastorek** [comment]
@jakubzzak  urobim to sposobom, ze bude ukazovat poslednych dajme tomu 50 znakov a pred tym 3 bodky.
