### ISSUE TITLE
návrh používateľského rozhrania = nakres

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#26]

**Comment by jakubzzak** [comment]
![image](https://user-images.githubusercontent.com/45845462/97995961-7e62ff00-1de7-11eb-8f64-27a29e98ae10.jpeg)

**Comment by jakubzzak** [comment]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/45845462/99001803-c696c580-253b-11eb-88b0-45fc640b2782.png">

**Comment by jakubzzak** [comment]
edit: https://app.moqups.com/aaMoA1NCxh/view/page/af62996ee

**Comment by jakubzzak** [comment]
Main
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/45845462/99803098-204d5000-2b39-11eb-9efe-2fdcb3fa3295.png">


Calibration dialog
<img width="792" alt="image" src="https://user-images.githubusercontent.com/45845462/99785148-0dc51d80-2b1d-11eb-8ba9-83399bf800e2.png">

latest GUI version, ready to be sent to client.. @MariaRiya

**Comment by jakubzzak** [comment]
calibration dialog

<img width="804" alt="image" src="https://user-images.githubusercontent.com/45845462/99784519-3993d380-2b1c-11eb-91d7-7041fd9b471d.png">
