### ISSUE TITLE
UML component diagram

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#29]

**Comment by janpastorek** [comment]
Robím na tom

https://cloud.smartdraw.com/share.aspx/?pubDocShare=832E622A8622A984A93B1A9D3DB9D2E37BF

**Comment by janpastorek** [comment]
https://online.visual-paradigm.com/w/iynyycbq/diagrams/?lightbox=1&highlight=0000ff&edit=https%3A%2F%2Fonline.visual-paradigm.com%2Fw%2Fiynyycbq%2Fdiagrams%2F%23diagram%3Aworkspace%3Diynyycbq%26proj%3D0%26type%3DComponentDiagram%26gallery%3D%2Frepository%2Fed8f369a-1164-4a60-8dde-ae8d9dda799c.xml%26name%3DOrder%2520Processing%2520System&layers=1&nav=1&title=Order%20Processing%20System#RU2FsdGVkX18KCp2X1BMYauzwKxouFjbSQq2l7hFErFGmFhuBIgXtcKlnyEOi3Z8Rs7B%2B%2Fwp4ZM4joY89SFg5tpohRRYOebtZ77OOdXSKu38hx2ny6iIxk0dHxb5WVF2b2Lro7NB7oHVDf42P9wwoWxa63iUk9OgBG1ONLvMssOM6RfvyJdGjnuFb4E1TLpDU6Szqgk9e0YsQP6OLkKKQBSyEL0iP%2FS5ycXYZ0dWFLD2XUvqyJdHtgJ8732U5INmOR2qxgh97KURNajoIDku3HHR6%2FR89UOC%2F8hBltCXaefjR5Iri20EpXn0ee6THyi9%2FBDTzB%2Fjk5N5n%2B7Zdn8ZiiDinAt9OtwOfIjcprOAOIcLRolpb1K6Hdq7Pri38MMoWB66bnJNUA9ZESx12OqIGwlVqalNT4fXei7BwcFUjfLfIQ7w6V%2FMECJZ13WlQSDfiUujyJ3orNWxtiadg3KDrydNgdCE8UpO4zehxy5sFYG%2Bomw6FZiZ9aNCBg7Ik9hHVuC5PkuQhx7u3VPGSnrTf3gml9Lp1d96KtHJIXi%2FSixUFSQTC%2BYTVqy38eFtgRyuccnuXfEgdAwb5hVpMtfvLEmRGX%2FrwV1Q6OfaTCcgf3dkLlfwApwVakVOkcT4uTKEwGSg4DSbzdjEJWO8owuhOmcl0QcPiwgYe7c4BkAwCorP9lckC2fmG%2B7pDgNtzfi1wZyvpWCH73A4oGzFIFIwIGI%2BAaavbgb3eVrWT8hWYcJLrhoSUbShnX5TQ8McqofgroWub2DGZvzxsZXuQsojAGpFgLqgpLDVUaerRT2D807XbrLv28x4dETZ%2FTZf%2BMC6MOqfHToYCWH3RVEJCUSl6kvh%2B%2FEfe8DUtjOGrsxHKRb4nQWSU2ugmPSYVofi3i2BWmUcFlkrotNZlsKRzZxAzDQvvz8tNKj%2FO8I8sEWyS0JsfvFoCT1OMZ5v%2BeYSH%2FDLIAVPVEzZe8DFpSroG8rKJaOo7V6MWybfEDXR%2BNCYO77WsSVQsQmedD84k2Nrvh7TJia9wSZKdloEsbT3vNoDglPZ0tJTBiYe8XBlAKyEW4HiHqFx%2B9TgZwujupj1jYA%2B8sUiIQIt0EplnU1x6ZVdoLNZBFZqKym0b0KxlQVsHIsBm0SeNHHi5jfKPk6YitaW35mEuvD2n2KJr7FCUDnSsV%2FmrlYn7e4Km9vfhp1g8cDEiIgLAjbiBtaGhGV%2FVTjfVL9p7Vwde2a67Vd2hPofxImaTTbNCieBp5eXQofI%2B4IAq7M79fF34BJrlSQpskWEZxQjfMcTq1IVw9kuJsRAnhgqsa%2BIV%2BjckO8u78V1IiS2n8r%2F5yI264rmGlb3T0GWrw8ZG0UY7SHvMyj0k6ebV%2FVDO4IHr5eet%2FIxv%2FuGhUwzarXrXLzTaVYLPJ1UbGT%2BLeTOdbC51jjiBCXuzdQFZ6xst%2Ffx0FcPGoslK7Bf2eDu%2BMzmbXTWPhdoCF8Io5GTSfe%2BFSxQIXk623Syzt9nczw4%2BwCTjjc8Lsoee511ITwRpNzNYsrNefzHhHPKNKsOQWcwHpOmNGJHZPfOB%2BBDhkfwj8%2BccRyvW4LJfxxx7gb6XFtXxgkgPiT6lkYlKVQ9UkAZ37RzvZmGA6rjfDw3DaNWoH85Uz5zsC59VM93T5mJPTsyFIWIRGA7kY8h7RToC7iJtJr4DIUrb3Zrt0DCQCbkiFvSFsVXZh6Ckw1Ue%2Br1AO4ovvaia8okY%2FnrXjCFe9GdckqgY0Yn78p1wh0w5wNsG8EhjhB4b%2FoBLKhejjCw%2FJtPvj%2BkfQJUf7aeT6dtZJDKI4ZscyDIYlXGtvbb12OhbPGJTEV1zVfbJq%2Bu17GlYln%2B412uKDzAe6SfmHufqQWtlKkEF%2B4F7v%2FqgnSlp6PlFDHvaY%2BApxnH435Vx1PaAIRPwCj96ZvumkaFmaekmd3nSbXRWnQUv5EE1lP2vIoqjAMMf18XzOVpvr7bHtDTmBMY%2Fda%2BErGj24BvS9MqbtKl6Lk8kaXzpONGECn%2Fyi96wOXH2i38%2BKGCtW2a8Kp0dr0jcUqda4pM3Yj40a5FpvWCWlIJQc%2FjXD0NWcP%2B3iCZZ7A2b%2Bpr9

**Comment by JanPastorek** [comment]
https://online.visual-paradigm.com/w/iynyycbq/diagrams/?lightbox=1&highlight=0000ff&edit=https%3A%2F%2Fonline.visual-paradigm.com%2Fw%2Fiynyycbq%2Fdiagrams%2F%23diagram%3Aworkspace%3Diynyycbq%26proj%3D0%26id%3D1&layers=1&nav=1&title=Komponent%20Diagram%20HP%204191a#RU2FsdGVkX1%2B06V5aFlHZ7ND%2FYelQEEazpgy3NdKsvItzjhOd4wlXz6ELR%2FTmEWPGWT8GZ3tWbyLTbrJfaib%2FFT5xuMO0jAE5P5Ealq0Sy1nKJ3Newypl0tUpdXYQsAO1R2Fm5%2B8B5J%2F%2BY4iKHXoVwMhwUIRHYAoLhzXxYdv1AhzgaH6aGn061pJvHjATUM8JVc2VZ0qADT1Ln7s%2BFyLvRMAiF9P3Mk6os9MLAkybhnc76C0oyrmNvFos14mLKIyIjiOvDcKnGFyCmI0r%2FB5fAge9B8AobcPAaFI3mlhnqCFZK%2BdQgO1tUzD6tv2iiNO0eRw3x37npo9%2FksqLVCo82Qke4vJTaoqPY%2FyREkIQ1JjVDOx5ARSWVqZMe2lEGnzoK7ynIrKGlH3K6ayA9i6c35qBN1HaXKy6CitgfhXN0Jr3hmnen9AM9m5UBZZdI8g2NUhEcIgZhTFQKm8xHcdnyrKhI5N4qK7P1Z2b2voHjlRbxV9gQX%2F3%2F%2Fz2Z0VRJXJ%2B6vt2lLPM7Mca%2FNEZ9ZyfxPxKLu%2BDZU71Y0Ow21liLDqVzZCrGl5okv%2BBifLY6MEDe%2BfjuK8vefEvfrEDA6C%2FL0yEQD%2B5xr%2Bdu52qX%2B1LKsmYhWaMCWFy0uUR0XTlKhdkHFo9erRQlC2egttDBkKmTplQ4SQr5wlGbCS2qltkXwY0yh%2Bo9Q67AdHR12US83NsttxBe4YiAjMVk%2BX4qkrVwZ2ralONcIXhk3n5FcX8LBhilvkAE1Y6jGPgqZiXpk6bk1CFcUutO4TdQZtNjjVvnlFMZwM6PXmsSqGX8mc31bfe%2BvbIR7VRNzEG%2Ba14wr7HdF%2BYTL%2BGFlMra9r7jp6fR%2BbZpCOsgTcqVXBEIqoxvH61wvMn6qAky4QMNtsFFVMdxAHbEtNH9wiFeRgis3H9u2V%2BEHsO5Ws%2B%2FE5TS38%2FjgOQapRTrZ1eTW%2FO4R%2BBawyGTq4o5zZ9%2FEs81E9RW%2Ble92MME%2Bv84RKMyEJtvoqbWPsWp9ZmNNLrX7W0T%2FVKshlPs7xvhFqQTbVCbNjdZYu9dmlIdmVoAiXUSbIY%2F0O1ae00rieHHmXip0ZK%2FVRFqBgDkgsXLo8w6fVyDeu6l9NN0L%2FCRiHsTT5hiAWbgbkezqo2Q5icWHnSDp1Ocktj%2FfN78psOVgIq0d0PsmpIOiu6c%2FAvyFBtkBR8mybyQAFMTEdLWDE7tj25wja8zAaGSsDGdhN0kbIOIdjZ8m68vEgGGeNcQ9pPmQ9i6N4z7BiQLLmOFl4pfNqrlbD7i1piEb0LfLp5rVJXjKxTWCcjK87hNu%2FVtzYUdPjsDkmk2OKxYMHS0xuZ%2Fjte7h3Ap5%2FDYTYz31JmCgK1PMk4VMvzb%2FaOtNUsMbpjvXUnEDJSi3TkSRwh8%2Bi3EB54iwcfiDbX7PlmLhDyb%2BJdva8Pz9tVTtdvRq1SZFxbz%2Fx0TrLfLZTTgzzAj1LzAXZHFKf5anRxewnbmdsbAPYGOaN9355RHL7kw5MmJGrq7%2BkQ5CALVO1CPZKW%2Fp9MdW1WYM35Hb5d74G8ih%2BzWryz4kw02RBmGB2R%2BGxfsg4E9NIn8d79YRiWxY4GfWTfywfCS4DpKLBfIJjqExn9x3aWvOyrmwzZJsOY%2BLdz6dLAEo29HWuq9BbGZ%2BvIcZ%2FY7Ey6llpM6lvFRrQ8JrV8sZSX9AgQUhvQYXfL3lYm4NybydMBBNNIbhD9Zawy59vXc1LxLPQwNlQ03TXUb3D0BAPhBhs4R9ybaPzrFI%2F3p%2FaLvHIapBtSAxU%2BBLEDgzK0NKWly94ipWU8XZpptlZxHMX%2Bdp2njWdelqKWgOYIqopGg0u9y9p2CytixHALrz6tUYqiVTgxViYTB%2Bha8DsIbJ2Ve8Ck6yM5WdAfeo5l7eAGJdzmstamLcYrT3YqsQrvNXNY6cvOdA6wpjPgyzjNQKKRDo%2FsGmiALKLC2Yqc6X7GkW7kUwF7SvvFf4K17r6b3WI3WyIu3arJbqegtPFT3qb%2FXNVpkLETag0plQUr1jtJEhMLbJZCydPAkOJWNsD7GQ7kp%2FeOrrAeEcn0OA4d12IVr%2F9ayTmhyt58%2BqReEupiEzPfkys3TuwRBRNtU24ZXaI64ygy%2BlktaYS6aa9IIsSHyyuWGfUC3AsURlvfpgSwlribQJR8gidWCO4MKoaKQdAYRX9MvYCYoGPV2RRP4SqmJH2MBD3Ru8XCf4ouS7yO%2FC%2F0X%2FIwQECKGY8Oh3bcN%2BMJe7AmQhd40cDBLke8x8t%2BwEqtkcakJA1eM9z1scCtTYsz6IYilWxgrbc5ZH3LBprt4sqW2LheDJn3aeSRwlDVHUIAQRgySy52g5K3h1%2BwrV%2BdZNZcWeSQh3DmdDCQLG67nMwGe2YcyCmHDK8ORbOQH0XSLs0iizARZ6wNDv6fN5Yxv5jTxsRKsLqaGUk43%2F9enQB%2Bxa%2BZmJDEm0IXJcYU%2F59lGB%2F886Cn22kTsVIPQXrd%2BplDDfS9L17ytBcy0kJ63%2FE92hAJPju%2FJ3MxC4v6NdwDjLjRS8oKfzai4LjqT3OP%2Fj4uRXcRe5%2Bh3aDhh4QA5Fn4U5maAvxGAZsG8fa0mVMeyLCkE%2FkRdjqMDUDnLFrth4H6ykYBZzdmJKrNs2Z3VhF%2BeShzMBKY2KFYQRdLnP%2B4JmiD%2FRxU5Ttucgtz6dTgHvd4T0b9wPzclaN0dD%2FMFoJ6kTXin%2FXUCeId%2BpLKVyiVcPPQk%2FpM7BIhjqCLSA6jt4%2BUD4ZkzGsoN7fBV%2FAEBvQfDwCiIvS9%2BkYjarmdzqRL6LLvP0cy54nB%2BcMRzJiVK%2FI%2BzrnPm3Xoax%2FNDvPYulOnjwcJyOHh9jRICvlpZr%2F%2B6kZxkePrzyhkL8ILKC2PB%2B5lGv7wJEiy%2Fy3t6LylkHcFrn9mVt8i5SoTiVpu9Ho9daHv2Jl9jbagagJZoKVFxc38LqyufEXpVlj7BEWK9LCOs7pmTpHL5%2FjqN65AiRejmrPNbaGp0clWSBC%2Fy27vSiHYYzw5reNp%2B5MZER5nuEgXqouQCxDWJbD8G1syPu5F0azxOQ5iKaHYyCGp1s7Q8ZICY%2BvUTwlMkfxWR5Ps5s2ee5MQi3HqpBdiAEouxNNWZTOmXUYNfsT10juz3zoGpuDYmfSPinkGeMoV02Q0wIwEnr44fVjgrCrjhhC2WT7JYAihveKgnnLRpeKE74A1LaqqBs3Iipfng2gbB39Ur5a9NRR6TSwn1l3ceemcDwEbMASC%2FcDPuJWfEUVskE3cMMsbH%2FvijpvldJ5LpRM%2BLvA%2FVHxDP%2B1rSzuGVeMJ4Mw0fcWld1Q89DLaXcz3RWFjnPgn0aYCNDnYvb4z3i%2F4oZGR13teBmJcdzSCmznYDQTWN%2FaoxeOj3UWCsaLLPGT68aL1uDwHh37tbdFAd4iChpP7Z2XyaiJMDlzR1IsDVacX0OEI%2BwUbhP6AXoiErUw5EKQ4XTR1idEwW6Qh96guWNydBYcKtUYTNwWoUMAMYUKAE6YCFDifEz6jbTjbbcbhqADCvQ3YDhm%2Fo%2Bh%2FDXDmuQ92fg3iH2zzpZwrblBWyRRWOAw9mbdP4YRp%2Ft2Geh4fP%2Fu3VtmA2SGJpZNrL9a92xGqZPGNtqYhYuDuUJxp6or09YnmtasLGVk9ofTrxPEz521FTDK5bav15cMtHJOuHcgAxOfxH%2FZlTfMazPC2XRCbk5W%2FM5dCeAkKWWyzs17iVvrXSLD1f5MS6KdG3WyuSVC%2Fc7CsCTkDYlgwWnm5muqobBNPJPIuzRo%2BZR2bdgu0SmGxy%2Fwpe4CLvD1mrq47TTrm5uSxzf187wVrx5hD0%2Fvtm%2BDHpLXgui7y1obixF%2FR1FLc72l0S1owBNWPlqBBccA9SgcItiA0T7ZBiYm9%2BqnHSlJnSeFxjI4M5pymFB2ncmgmBwLupElSQJKyut6TKpKIuh5JZQkx6JsXukZo37aGGrXVnpukVLMPvBmQcgm1PUaBYZwJPvEvAlxW7khKCzy6nLT%2BomLSBVg2irrY2Rijd7ljFKvkUJPOgLFtWxgfSxzRA8hulY48XIxzKKu4T2qEIXrFYwshv5wxq55coh8ut8SPzMhkueU8ZG%2FE6KvvCkyVHe2s9VCCjLP2gSratyf6mS5AX85pUb9td6y6%2FPJ9i6JRQCeqhiWNAMQ2dThCSgGpPw91lp%2FvOyGbdfs807DO5UNmplAPp5Q1z%2FeuLY9bGcnubUef%2BCZqO92PpDzmXpZtjzRJvjR%2F4g5nCSNzzShjTsb2rwJyvP3u6B6Wth1x57hfvpWrP4exMSleCexNieYg%2Fba46s6vkB%2FfiqkUdhQaXUDPvBPOaEt06ahif%2BVRUuX2UwHDM1IUi6jzr99%2Br0k1Mno%2B9vnkBAUIan%2F4rvhkdXJyaZChNkAzA8MWSj30rVF2C16eue9UtmtYUT8qC8%2Fjhg%2FAy2CaToFGVB1hGFgxQ7KLNUyrLuUNYRnAi%2FNjTtEoQ28jbAm4dDYz12B7

**Comment by jakubzzak** [comment]
@janpastorek nevidim to, nevim sa tam dostat, skus hodit screenshot

**Comment by jakubzzak** [comment]
@janpastorek z toho linku nemame ziadny esteticky zažitok, treba davat tie veci priamo do komentarov ak sa daju

![component-diagram](https://user-images.githubusercontent.com/45845462/100390740-bac5fb80-3031-11eb-8e50-d9ea2752594b.png)

**Comment by JanPastorek** [comment]
![image](https://user-images.githubusercontent.com/21310363/100448121-1fc13600-30b2-11eb-91a2-44be60d6d22e.png)

**Comment by JanPastorek** [comment]
komentare ku kominkacii medzi komponentmi a detail. info o komponentoch je v dokumente navrh uz
