### ISSUE TITLE
UML class diagram

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#30]

**Comment by MariaRiya** [comment]
https://drive.google.com/file/d/1wCphPN5A1ZJufzc3jEvgSJrrD6x1vmAX/view?usp=sharing

**Comment by jakubzzak** [comment]
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/45845462/100445570-9b6cb400-30ad-11eb-8429-6f1b36a0e6dc.png">

tiez mam otazku, ci by nebolo fajn oddelit objekty aku su File, Measurement, Graph.. od ich services => funkcie pre pracu s nimi, teda vytvorit dalsie Entity called; FileService pre pracu s File, GraphService...

**Comment by pavelpetrovic** [comment]
na prvý pohľad sa mi zdá, že netreba, ale nevidím to dostatočne celistvo.

**Comment by jakubzzak** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/45845462/101981848-11594980-3c70-11eb-8b1b-7df8fdeab1a8.png">

lates version
edit at: https://app.creately.com/diagram/Kzyguo7PV2x/edit
