### ISSUE TITLE
generate documentation

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#304]

**Comment by N4gyR** [comment]
[LCR 4191a JavaDoc.zip](https://github.com/TIS2020-FMFI/hp/files/5972188/LCR.4191a.JavaDoc.zip)

@pavelpetrovic

**Comment by pavelpetrovic** [comment]
vďaka, veľmi sa teším a dali ste to aj niekde priamo do repozitára na github?
