### ISSUE TITLE
path to hpctrl.exe

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2020-FMFI/hp#309]
neviem ako sa nam toto podarilo, ale v zdrojakoch je natvrdo "C:/s/hp/hpctrl.exe"
fixnite to, prosim, aby sme to mohli so zadavatelom nabuduce ked pride do skoly otestovat.
nech sa taha z aktualneho adresara.
vychadzajte z balika https://kempelen.dai.fmph.uniba.sk/HP.zip
vdaka.

**Comment by jakubzzak** [comment]
@pavelpetrovic pokusim sa, dam vediet
