### ISSUE TITLE
UML state alebo UML sequence diagram

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#31]

**Comment by MariaRiya** [comment]
Skusila som zacat s UML state diagram
https://drive.google.com/file/d/1Lz6DK-M2lwivlJ5Th3A--B-OolGSXWu3/view?usp=sharing

**Comment by MariaRiya** [comment]
prerobila som state diagram pre jedno meranie.
https://drive.google.com/file/d/1z3c310YZZ-8PHOdiPJiBkaUDwmd8cLvY/view?usp=sharing

**Comment by MariaRiya** [comment]
pribudla nova verzia state diagramu
https://drive.google.com/file/d/1RR9cjtJ-MEGM2hTDavzVxweJjnEJV4jK/view?usp=sharing

**Comment by jakubzzak** [comment]
Inak, staci uml state pre measurement? Netreba aj v akych stavoch sa nachadza program?

**Comment by MariaRiya** [comment]
https://drive.google.com/file/d/1LB4emDvjZWqvRnlaaTwrG5SVHfoWhTa3/view?usp=sharing

**Comment by pavelpetrovic** [comment]
dakujem, stavovy prechod medzi loaded a saved nie je popisany. 
su dve moznosti:
1. bude tam iba "closed or new measurement started" - cize zatvori sa ta aplikacia, alebo sa zacne nove meranie, ktore je uz ine, takze opustame tento diagram
2. okrem toho tam bude aj druhy paralelny stavovy prechod "saved" - ak aplikacia dovoli znovu ulozit aj nacitane meranie (umozni?)

este sa mi zda, ze tam pred stavom "measurement in progress" chyba jeden stav "measurement is being configured", ked sa nastavuje predtym, ako sa spusti (predpokladam, ze sa bude dat nieco nastavit, predtym ako sa spusti meranie?)

**Comment by jakubzzak** [comment]
@pavelpetrovic rozumieme, dakujeme za review, co sa tyka bodu c. 2, s ulozenym meranim mozme pracovat, zavriet ho, alebo ho nacitat. mozno by sme mohli spravit editaciu komentarov ku konkretnemu meraniu, v tom pripade by loaded measurement mohol byt znova ulozeny, inak nie

**Comment by MariaRiya** [comment]
https://drive.google.com/file/d/1wYM_RpRyuZqVsDdVGpvzFr03Iej2MwwP/view?usp=sharing

**Comment by JanPastorek** [comment]
hmm myslim, ze teraz to je uz zrozumitelne
