### ISSUE TITLE
testovacie scenáre

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#34]

**Comment by MariaRiya** [comment]
https://drive.google.com/file/d/1eIeBfSiGXf28uC8E_7InZOx3gxRRXjvK/view?usp=sharing

**Comment by pavelpetrovic** [comment]
* pekné, ďakujem. akurát v bode "Ak je to potrebné, upraví ostatné nastavenia" by sa dalo trochu viacej rozviesť možnosti - možno vytvoriť z toho viacero scenárov?
* potom neskôr nakoniec by ste do tých scenárov mohli pridať aj obrázky, ako to má vyzerať, aby človek, ktorý potom neskôr podľa toho bude testovať, vedel ako to má vyzerať, keď to chce skontrolovať... (inak by bolo treba trochu lepšie popísať, čo je výsledkom tých krokov, napr. keď sa niečo zmeria)
