### ISSUE TITLE
Rozdelenie úloh implementácie

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#35]

**Comment by jakubzzak** [comment]
Implementacia bola rozdelena na co najviac mozne nazavisle casti a priradene clenom timu, ktori su za tieto casti zodpovedni:

@janpastorek - incoming data handling and graph visualisation
- [x] graph visualisation
- [x] zoom in/out graph
- [x] move around in graph
- [x] save as graph
- [x] double axis
- [x] real time plotting
- [x] performance optimalization
- [ ] if auto sweep off, show step buttons < > below graph -> discuss whether necessary
- [x] graph load buttons
- [x] parsing incoming data and saving it as a data structure -> @N4gyR 
- [ ] final tests of this part

@MariaRiya - persistent data handling, measurement parameters initialisation
- [x] config file handing
- [ ] creating measurement data file
- [x] change auto saving directory in toolbar
- [x] auto saving button functionality: off/on
- [ ] final tests of this part

@N4gyR - wrapper, app-machine communication
- [x] create wrapper
- [x] run sending commands and handle receiving data
- [ ] try it with machine -> @pavelpetrovic 
- [ ] final tests of this part

@jakubzzak - implementation organisation, code supervising
- [x] app skeleton
- [x] gui main, calibration
- [x] notification
- [x] calibration
- [x] help
- [ ] check on everything above
