### ISSUE TITLE
Gpib comunication and machine handling

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#44]
connect machine with the app and transport commands

**Comment by jakubzzak** [comment]
- [ ] communication via lib.exe -> create wrapper
##
- [ ] try to connect on app open -> notification
##
- [ ] database of commands

- [ ] create enum

- [ ] get string command

**Comment by pavelpetrovic** [comment]
hpctrl console app has been moved to its own repository: https://github.com/TIS2020-FMFI/hpctrl

Please find a place within your folder structure where you will download it with
git clone https://github.com/TIS2020-FMFI/hpctrl.git

and make a note about that in your readme file.

**Comment by pavelpetrovic** [comment]
Len poslušne hlásim, že sme otestovali, že the hpctrl funguje rovnako aj na tej PCI karte National Instruments rovnako ako na tom externom USB zariadeni.
