### ISSUE TITLE
Naformulovat presny katalog poziadaviek

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#5]
@pavelpetrovic 
https://drive.google.com/file/d/1de-93VMZhMHgE5Q3-E3uJ561TpBfb91y/view?usp=sharing

**Comment by janpastorek** [comment]
Stretli sme sa 1.10.2020 , predbezne informacie a predstavu mame

**Comment by pavelpetrovic** [comment]
*  pridat do 1.4 aj odkazy na softver, kde su zdrojaky (vsetky su k dispozicii)
* vysvetlit podrobne ako sa prevedie aj ako sa pouzije vysledok kalibracie v casti 3
* preformulovat cast 2 aby to boli vety nie hesla, netreba aby boli cislovane
* v 2.1. "základnou úlohou bude spojazdnenie ovládania GPIB USB karty na prepojenie "
dokument nie su poziadavky na vyvojovy tim, ale na aplikaciu
ale zaroven tam urobte komentar o tom, co su dvojice meranych hodnot
* z 2.2.6. nerozumiem ci frequency sweep a voltage sweep su vylucujuce sa alternativy, alebo sa nastavuju oboje,
* tiez nerozumiem, ci start stop step a spot sa nastavuju vsetky, alebo ci si mam z nich vybrat jeden
* k 2.2.7 prosim pridat priklady obrazkov
* 2.2.8 a 2.2.4 sa zda byt duplicita, ale prepiste to prosim cele plnymi vetami
* v 2.4 mozete pridat, ze sa to pusta pod OS Windows a je to bezna desktopova aplikacia
* v 3.1.1 myslim si, ze softver bude komunikovat s pristrojom cez pripojeny Keysight - jediny pripojeny, netreba nic vyberat ani zadavat adresu
* v 3.1.2. odporucam zuzit rozhranie iba na Keysight zatial a pripadne tie dalsie karty oznacit nizsou prioritou
* v 3.1.3. vymenovat ktore veliciny 
* 3.1.4.3. ake su tie krajne moznosti rozsahov pre kazdu velicinu
* 3.1.5 kombinovane poziadavky - treba rozbit na jednotlive
* 3.1.6 nerozumiem C D alebo R X
* 3.1.8. silno odporucam data z merania najskor ukladat iba do pamate a az potom na poziadavku do suboru
* 3.1.10 syntax error: prvykrat v dokumente vidim, ze budu dva grafy, ale preco? ake?

**Comment by JanPastorek** [comment]
Komentare, comu nerozumieme kazdy

https://drive.google.com/file/d/1hE4KlCchChdK50rDrc-UywzmaXHC5LV8/view?usp=sharing

**Comment by MariaRiya** [comment]
https://drive.google.com/file/d/1MnFojxU0SvX-9hmi_34YaZ5MZMXzvzpd/view?usp=sharing
subor s komentarmi od zadavatelovi aj odo mna

**Comment by MariaRiya** [comment]
mame novsiu verziu katalogu, pribudli komentare od zadavatela
https://drive.google.com/file/d/1nPXEwoxuGo6-i5RXk_NmC_Z8fx4xRLfT/view?usp=sharing

**Comment by pavelpetrovic** [comment]
Mám takúto správu od zadávateľa:

"ohladom toho  biasu by som to zhrnul tak, ze aj ked sa pouziva menej su
merania kde toto nastavenie je velmi  dolezite. Ak to teda  nie je narocne
tak by som ponechal tuto funkciu v programe s tym ze ak by bol problem v
grafickom zobrazeni (aj ked malo by ist len o vymenu x-vej osy)  tak aspon
aby sa vysledky ukladali do suboru."

To znamená, prosím:
* ponechajte v programe nastavovanie všetkých 4 parametrov BIASu
* umožnite SWEEP aj v režime BIAS, nielen v režime frekvencií, zobrazte to v grafe (na X-ovej osi budú V namiesto MHz) a ukladajte to aj do súboru.
* upravte prosím Katalóg požiadaviek, návrh používateľského rozhrania a Návrh, aby to bolo všade v súlade s touto predstavou, ďakujem.

Inak už prišli karty NI, začiatkom týždňa vyskúšam, ale zatiaľ to vyzerá tak, že pre Vás by to nemalo znamenať žiadne zmeny.
Veľa zdaru!

**Comment by jakubzzak** [comment]
v1.6 https://drive.google.com/file/d/1GO1iM5shoZ2fI4xkbNjyiIC3y68FHrpP/view?usp=sharing

**Comment by pavelpetrovic** [comment]
tento KP je dosť nekvalitne napísaný. Opravte prosim aspoň tieto drobnosti:

 - veličinín => veličín
 - odkazy v 3.1.4 sú na neexistujúce sekcie
 - toto znamená čo? "Pri akýchkoľvek komplikáciách s grafom môže byť nasadená tabuľka,"
   (dajte to preč, alebo to vysvetlite)
 - Toto nesedí: "Po ukončení merania sa dáta automaticky uložia, ak je nastavené automatické ukladanie."
    automatické ukladanie má fungovať už počas merania, nie až po ukončení merania
 - chýba mi informácia o tom, čo sa deje s grafom, keď postupne hodnoty pribúdajú
 - nikde nevidím napísané, že si používateľ bude môcť vyberať, či meria podľa bias (V) alebo podľa frekvencie (MHz)
 - co znamena "[format]" v 3.1.5?
 - a co znamena "s názvom: čas-typMerania(meraná kombinácia napr. C-R)" ?
 - co znamena "bude dať výsledný graf exportovať."?

**Comment by JanPastorek** [comment]
drobnosti opravené, uznávam nie je to najkrajší dokument. Trochu som ešte nejaké duplicity a formátovanie poupravoval.

**Comment by pavelpetrovic** [comment]
Ďakujem. Stále je tam napísané: "Po ukončení merania sa dáta automaticky uložia, ak je nastavené automatické ukladanie." ale pamätám sa, že pri jednom z posledných hovorov si zadávateľ želal, aby sa dáta ukladali hneď priebežne počas merania. Predstavte si, že nechá experiment bežať dva dni v kuse a chce si byť istý, že sa tie dáta, ktoré sú už namerané uložili, aj keď meranie ešte beží a neskôr sa niečo pokazí. (súbor treba za každým pridaným riadkom znovu zatvoriť, aby sa to korektne zapísalo do súborového systému). Mohli by ste, prosím, zohľadniť aj ostatné body v mojej predchádzajúcej správe?

**Comment by jakubzzak** [comment]
ak ma cisla neklamu, najdlhsie meranie by malo trvat 3h, v kazdom pripade si nemyslim, ze ukladanie kazdej hodnoty bude performance friendly, nebolo by rozumnejsie ukladat mozno raz za minutu? alebo kazdych 10sec?

**Comment by MariaRiya** [comment]
Zadávateľ schválil aktualizáciu katalógu požiadaviek
