### ISSUE TITLE
graph in scenebuilder

### ISSUE THREAD

**Issue by JanPastorek** [TIS2020-FMFI/hp#60]

**Comment by jakubzzak** [comment]
@janpastorek great job, there is still odd behaviour when scrolling the graph, have a look at https://www.jfree.org/forum/viewtopic.php?t=29166, how to implement your own chart mouse listener

**Comment by jakubzzak** [comment]
I noticed that graph auto move is off once u zoom in/out while measurement in progress, what if we would not allowed user to zoom in/out until the measurement is done
