### ISSUE TITLE
auto sweep off measurement

### ISSUE THREAD

**Issue by jakubzzak** [TIS2020-FMFI/hp#91]
change point to 'next'
next only visible if auto sweep off

**Comment by JanPastorek** [comment]
@N4gyR, @MariaRiya , @jakubzzak aka  je funkcia, ktorá mi dá nové dáta? respektiva funkcia ktora vrati novy riadok nameranych dat zo stroja?

**Comment by jakubzzak** [comment]
@janpastorek, pri autosweep off? 
@N4gyR co na to hovoríš?

**Comment by JanPastorek** [comment]
@jakubzzak  autosweep on aj pre off, mne sa totiz implementacia nijako v podstate nezmeni, iba pridavam data

**Comment by N4gyR** [comment]
@janpastorek v machineCommunication/Connection je metóda startMeasurement() ktora obsahuje "TODO" kde treba len doplnit kam by tie dáta mali ísť

**Comment by JanPastorek** [comment]
it should disappear in abort, waiting for -> @jakubzzak,  v mainController tam treba doprogramovat metodu point, cize poziadat stroj o jedno meranie a zapisat jeden riadok dat do SingleValue -> @N4gyR

**Comment by jakubzzak** [comment]
@janpastorek ako sme na tom s tymt issue?

**Comment by JanPastorek** [comment]
@jakubzzak point button som nakodil, a vyhadzoval sa spravne, po spusteni Run, ked je vypnutz auto sweep. Ci to bude fungovat na realnych datach, neviem, to uz potom kodil @N4gyR  v mainControlleri  metoda point().

asi vsak neni nastavene, aby zmizol po abort, lebo vtedy abort nebol
